module.exports = {
    docters: 'hospital',
    patient: 'patient',
    patient_level: 'patient_level',
    basic: 'patient_basic_info',
    general: 'patient_general_info',
    maternal: 'patient_maternal_info',
    baby_appears: 'patient_baby_appears_info',
    baby_resp: 'patient_baby_resp_info',
    baby_cv: 'patient_baby_cv_info',
    baby_cns: 'patient_baby_cns_info',
    baby_git: 'patient_baby_git_info',
    baby_investigation: 'patient_baby_investigation',
    baby_final: 'patient_baby_final',
    baby_antibiotic: 'patient_baby_antibiotic',
    hospital:'m_hospital',
    user:'m_users',
    map_user_role:'map_user_role',
    map_user_module_permission:'map_user_module_permission',
    hospital_branch:'m_hospitals_branch',
    roles:'m_roles',
    speciality:'m_speciality',
    user_type:'m_user_type',
    hospital_branch_roles:'m_hospital_branch_roles',
    hospital_branch_speciality:'m_hospital_branch_speciality',
    staff:'m_staff',
    state:'m_states',
    hospital_staff:'map_staff_hospitals',
    staff_permission:'map_user_permissions',
    permission :'m_permission',
    patient_infos:'patient_infos',
    referral_doctor:'m_referral_doctors',
    referral_hospitals:'map_referral_hospitals',
    messages:'t_message_logs',
    staff_referral_hospital:'map_staff_referral_hospitals',
    refferal_opinion:'m_referral_opinion',
    referral_files:'map_referral_files'
  };
  