module.exports = {
  not_found_msg: 'Record not found',
  not_found_status: 404,
  invalid_credential_msg: 'username or password  is invalid.',
  credential_required:'Username / Password is required',
  password_required: 'password is required.',
  password_not_match: 'passwords do not match.',
  login_success: 'user found & logged in.',
  username_alreay_taken_msg: 'username is already exists.',
  user_already_exist: 'User is already exists!',
  email_alreay_taken_msg: 'email is already exists.',
  username_alreay_taken_status: 422,
  signup_success: 'user created successfully.',
  common_required: 'required have data',
  bcrypt_solt_text: 12,
  patient_alreay_taken_msg: 'patient is already exists.',
  patient_success: 'patient created successfully.',
  get_patients_success: 'get all patients successfully.',
  get_baby_git_success: 'get all baby git successfully.',
  patient_basic_success: 'Successfully Inserted !',
  get_level: ' level info',
  success: 'success',
  field_empty_msg:'Field must not be empty',
  field_int_msg:'Must be an integer value',
  field_not_exist:'Field does not exist',
  field_string_msg:'Must be string value',
  data_created_successfully:'Data Insertion Successfull!',
  data_updated_successfully:'Data Updated Successfully!' ,
  error_msg:'Internal Server Error',
  no_record_found:'No Record Found',
  no_maternal_record_found:'Please fill mother profile',
  record_already_exist :'Record already exist',
  user_already_exit:'User already Exit',
  successfully_registered:'Registration successfull',
  hospital_branch_creation:'Hospital branch created successfully',
  role_add_successfully:'Role added successfully',
  speciality_add_successfully:'Speciality added successfully',
  speciality_updated_successfully:'Speciality updated successfully',
  staff_add_successfull:'Staff Added Successfully!',
  staff_updated_successfully:'Staff Updated Successfully',
  hospital_profile_updated_successfully:'Hospital profile updated successfully',
  message_send:'Message send Successfully',
  email_sent:'Email is sent Successfully',
  email_validation:'Email id already exist !',
  contact_validation :'Contact no already exist!',
  status_update:'Status updated successfully !',
  referral_select :'Referral selected successfully for opinion',
  score_message : 'Score generation is in progress. Please wait for some time. !',
  colShift: 5, //should be greater then 2 to avoid errors
  rowShift: 5,
  svgFontSize: 30,
  svgWidth:500,
  avyantra_email: 'avyantra@gmail.com'
}