import table_const from '../config/table'
module.exports = (sequelize, type) => {
  return sequelize.define(table_const.baby_final, {
    id: {
      type: type.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    study_id: type.INTEGER,
    days_of_stay_in_hospital: type.STRING,
    final_diagnosis_sepsis: type.STRING,
    final_diagnosis_rds: type.STRING,
    final_diagnosis_ttnb: type.STRING,
    final_diagnosis_jaundice: type.STRING,
    final_diagnosis_lbw: type.STRING,
   // final_diagnosis_lga: type.STRING,
   // final_diagnosis_aga: type.STRING,
    final_diagnosis_anemia: type.STRING,
    final_diagnosis_dextochordia: type.STRING,
    final_diagnosis_hypoglycemia: type.STRING,
    final_diagnosis_hypocalcemia: type.STRING,
    final_diagnosis_gastroenteritis: type.STRING,
    final_diagnosis_perinatal_respiratory_depression: type.STRING,
    final_diagnosis_shock: type.STRING,
    final_diagnosis_feeding_intolerence: type.STRING,
    final_diagnosis_thrombocytopenia: type.STRING,
    final_diagnosis_eos_los: type.STRING,
    final_diagnosis_other: type.STRING,
    final_diagnosis_pulmonary_hemerrage: type.STRING,
   // final_diagnosis_sga: type.STRING,
    baby_discharge_date: type.STRING,
    reading: type.STRING ,
    // final_diagnosis_lga:type.STRING,
    // final_diagnosis_aga:type.STRING,
    // final_diagnosis_sga:type.STRING

    final_diagnosis_meningitis:type.STRING ,
    final_diagnosis_hypoxia:type.STRING,
    final_diagnosis_metabolic_acidosis:type.STRING,
    final_diagnosis_asphyxia:type.STRING,
    final_diagnosis_septic_arthritis:type.STRING,
    final_diagnosis_endocarditis:type.STRING,
    final_diagnosis_peritonitis:type.STRING,
    final_diagnosis_soft_tissue_abscess:type.STRING,
    final_diagnosis_coagulopathy:type.STRING,
    final_diagnosis_uti :type.STRING,
    final_diagnosis_umblical_sepsis:type.STRING,
    final_diagnosis_bleeding_manifestation:type.STRING,
    final_diagnosis_central_peripheral :type.STRING,
    final_lga_sga_aga_suspect:type.STRING,
  //  hypoxia:type.STRING,
   // metabolic_acidosis:type.STRING,
   // rupture_time:type.STRING,
    discharge_status:type.STRING,
    final_diagnosis_skin_pustules:type.STRING,
    final_diagnosis_seizures:type.STRING,
    final_diagnosis_pneumonia:type.STRING,
    final_diagnosis_pulmonary_hemorrhage:type.STRING,

   });
};
